AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  System for Automated Data Normalization and Verification.

Resources:
  RawDataBucket:
    Type: AWS::S3::Bucket

  DataProcessingFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.14
      CodeUri: ./src
      MemorySize: 512
      Timeout: 60
      Layers:
        - arn:aws:lambda:us-east-2:336392948345:layer:AWSSDKPandas-Python314:2
      Events:
        FileUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref RawDataBucket
            Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref RawDataBucket
        - S3WritePolicy:
            BucketName: !Ref RawDataBucket
        - Statement:
            - Effect: Allow
              Action: 'bedrock:InvokeModel'
              Resource: '*'